filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - /app/logs/*.log
  parsers:
    - ndjson:
        overwrite_keys: true

setup.ilm.enabled: true
setup.template.enabled: true
setup.template.type: data_stream

setup.template.name: "filebeat-datastream-%{[agent.version]}"
setup.template.pattern: "filebeat-datastream-*"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: filebeat-datastream-%{[agent.version]}

setup.kibana:
  host: "http://kibana:5601"