version: '3.9'

services:
  # DB
  mssql-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPassword!123
      - MSSQL_PID=Developer
      - TZ=Asia/Taipei
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./initDb:/usr/config
    restart: always
    command: >
      /bin/bash -c "/opt/mssql/bin/sqlservr & sleep 15 && /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P StrongPassword!123 -C -i /usr/config/init.sql && wait"

  # API Service
  api-service:
    build:
      context: ./api-service
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - TZ=Asia/Taipei
      - PORT=8080
      - DemoDb=sqlserver://sa:StrongPassword!123@mssql-db:1433?database=DemoDb&encrypt=disable
    volumes:
      - ./api-service:/app
      - log-data:/logs
    depends_on:
      - mssql-db

  # ELK
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - TZ=Asia/Taipei
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:9200/_cat/health"]
      interval: 3s
      timeout: 3s
      retries: 80
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.3
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - 5601:5601
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/api/status"]
      interval: 3s
      timeout: 3s
      retries: 80
    depends_on:
      elasticsearch:
        condition: service_healthy

  filebeat:
    image: docker.elastic.co/beats/filebeat:9.0.3
    user: root
    command: ["filebeat", "-e", "--strict.perms=false"]
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - log-data:/app/logs:ro
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy

volumes:
  mssql_data:
  log-data:
  esdata: