definitions:
  models.Admin:
    properties:
      adminId:
        type: integer
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - name
    - password
    type: object
  models.User:
    properties:
      age:
        type: integer
      createDateTime:
        type: string
      id:
        type: integer
      name:
        type: string
    required:
    - name
    type: object
info:
  contact: {}
paths:
  /CreateUser:
    post:
      consumes:
      - application/json
      description: 由管理員建立新使用者
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 使用者資料
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema: {}
      summary: 建立新使用者
      tags:
      - User
  /DeleteUser/{userId}:
    delete:
      consumes:
      - application/json
      description: 由管理員刪除指定 ID 的使用者
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 使用者ID
        in: path
        name: userId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema: {}
      summary: 刪除使用者
      tags:
      - User
  /GetUser/{userId}:
    get:
      consumes:
      - application/json
      description: 由管理員查詢指定 ID 的使用者
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 使用者ID
        in: path
        name: userId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema: {}
      summary: 取得單一使用者
      tags:
      - User
  /GetUsers:
    get:
      consumes:
      - application/json
      description: 由管理員查詢所有使用者
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "400":
          description: Bad Request
          schema: {}
      summary: 取得所有使用者
      tags:
      - User
  /SignUpAdmin:
    post:
      consumes:
      - application/json
      description: 註冊新的管理員帳號
      parameters:
      - description: 管理員資訊
        in: body
        name: admin
        required: true
        schema:
          $ref: '#/definitions/models.Admin'
      produces:
      - application/json
      responses:
        "201":
          description: 註冊成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 參數錯誤
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 註冊失敗
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Admin 註冊
      tags:
      - admin
  /UpdateUser/{userId}:
    put:
      consumes:
      - application/json
      description: 由管理員更新指定 ID 的使用者資料
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 使用者ID
        in: path
        name: userId
        required: true
        type: integer
      - description: 使用者資料
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema: {}
      summary: 更新使用者
      tags:
      - User
swagger: "2.0"
